version: '3.8'
services:
  application-db:
    image: postgres:15.3-alpine
    restart: no
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=tinydms
    ports:
      - '5432:5432'
    volumes:
      - ./application-db:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_RELATIVE_PATH: /auth

    command:
      - start-dev
      - --import-realm
    volumes:
#      - ./realm.json:/opt/keycloak/data/import/realm.json
      - ./keycloak.conf:/opt/keycloak/conf/keycloak.conf


  keycloak-db:
    image: postgres:15.3-alpine
    restart: no
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak
      - POSTGRES_DB=keycloak
    ports:
      - '55432:5432'
    volumes:
      - ./keycloak-db:/var/lib/postgresql/data

volumes:
  db:
    driver: local